[package]
name = "streamflow_mock"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "streamflow_mock"

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
bytemuck = { workspace = true }
