name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build devcontainer image
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          tags: damm-honorary-dev:latest
          load: true
      - name: Run tests in container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace damm-honorary-dev:latest bash -lc "./scripts/setup-local.sh && ./scripts/deploy-local.sh && ./scripts/run-tests.sh"
